### ISSUE TITLE
Discussion about generic_exclusions

### ISSUE THREAD

**Issue by pablodav** [deajan/linuxscripts#2]
https://github.com/deajan/linuxscripts/blob/f591b892474b9e7950cf27f7295b1a157db3c9b4/burp/incexc/generic_exclusions#L2

Hi deajan,

Do you know if this exclusion really works?

If I test it here: https://regex101.com/ 

It doesn't, and tells there are warnings. 

I'm not too familiarized with regex, it is something I don't use often just for very specific cases when I need it.

in the test there, it looks to work:

    exclude_regex = ^.*[\/\\](~\$.*)\.*$

But I'm not sure if it is correct

**Comment by pablodav** [comment]
this was reviewed during https://github.com/CoffeeITWorks/ansible_burp2_server/issues/40

**Comment by deajan** [comment]
Wow... I'm sorry Pablo, I've found this issue only because another one was opened, somehow missed the notification about it, so never saw it :(

I've checked the regex, it works on regex101 but you'll have to change the delimiter first, since '/' can't be used.

Btw, the ruleset has largely evolved (mostly for Windows clients). You may want to update.
